volumes:
  logs_data:
    driver: local
  download_data:
    driver: local
  instance_data:
    driver: local

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - logs_data:/app/logs
      - download_data:/app/downloads
      - instance_data:/app/instance
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server
