import argparse
import os
import logging


from playwright.sync_api import sync_playwright
from dotenv import load_dotenv

target_dir = "/app/cookies/cookies.txt"

logFormatter = logging.Formatter("%(asctime)s [%(levelname)-5.5s]  %(message)s")
logger = logging.getLogger()

fileHandler = logging.FileHandler("cookie_generator.log")
fileHandler.setFormatter(logFormatter)
logger.addHandler(fileHandler)
fileHandler.setFormatter(logFormatter)
logger.addHandler(fileHandler)

consoleHandler = logging.StreamHandler()
consoleHandler.setFormatter(logFormatter)
logger.addHandler(consoleHandler)

logger.setLevel(logging.INFO)

load_dotenv()
GOOGLE_EMAIL = os.getenv("GOOGLE_EMAIL")
GOOGLE_PW = os.getenv("GOOGLE_PW")

parser = argparse.ArgumentParser(description='Generate cookies for YouTube')
parser.add_argument('-m', '--manual', action='store_false', help='Run browser in manual mode')
args = parser.parse_args()
HEADLESS = args.manual

if not HEADLESS:
    Headless = False


def save_cookies_to_file(cookies, filename="cookies.txt"):
    """Save cookies to a Netscape-format cookies.txt file."""
    with open(filename, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by a script\n\n")
        for cookie in cookies:
            domain = cookie.get('domain', '')
            include_subdomains = "TRUE" if domain.startswith('.') else "FALSE"
            path = cookie.get('path', '/')
            secure = "TRUE" if cookie.get('secure', False) else "FALSE"
            expires = str(int(cookie['expires'])) if cookie['expires'] != -1 else "0"
            name = cookie.get('name', '')
            value = cookie.get('value', '')
            f.write(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")


def run(playwright):
    """
    Logs into a Google account via YouTube using Playwright, navigates to a video, and extracts cookies.

    This function automates the process of logging into a YouTube account, accessing a video page,
    and extracting cookies from the session. The extracted cookies are then saved to a specified
    target directory.

    :param playwright: The Playwright instance used for browser automation.
    :type playwright: playwright.sync_api.sync_playwright
    :return: None
    """

    logger.info("Generating cookies...")
    browser = playwright.chromium.launch(headless=HEADLESS)
    context = browser.new_context()
    page = context.new_page()

    logger.info("Trying to log in")
    #Logging in here
    try:
        page.goto("https://accounts.google.com/ServiceLogin?service=youtube&continue=https://www.youtube.com/")

        # 1. Wait for Google's specific email input ID
        page.wait_for_selector('#identifierId', state="visible")

        # 2. Click it to focus the element (simulating human interaction)
        page.locator('#identifierId').click()

        # 3. Use press_sequentially to type it out like a human (helps bypass basic bot checks)
        page.locator('#identifierId').press_sequentially(GOOGLE_EMAIL, delay=50)

        # 4. Click the Next button
        page.locator("button:has-text('Weiter'), button:has-text('Next')").first.click()

        # Wait for the password field to appear (Google uses a different selector for this)
        page.wait_for_selector('input[type="password"]', state="visible")
        page.locator('input[type="password"]').click()
        page.locator('input[type="password"]').press_sequentially(GOOGLE_PW, delay=50)

        page.locator("button:has-text('Weiter'), button:has-text('Next')").first.click()

        page.wait_for_url("https://www.youtube.com/**", timeout=30000)

    except Exception as e:
        logger.critical(f"Error logging in: {e}")
        exit(0)


    except Exception as e:
        logger.critical(f"Error logging in: {e}")
        exit(0)

    #Trying to get a video and extrack cookies
    logger.info("Starting video and extract cookies...")
    try:
        page.goto("https://www.youtube.com/watch?v=-fCtvurGDD8")

        page.wait_for_selector("video", state="visible", timeout=30000)
        page.wait_for_timeout(2000)

        cookies = context.cookies()

        save_cookies_to_file(cookies, target_dir)
        logger.info(f"Cookies saved to {target_dir}")
    except Exception as e:
        logger.critical(f"Couldn't save cookies: {e}")
        exit(0)


    browser.close()

with sync_playwright() as p:

    run(p)